# Generated by Django 5.0.6 on 2024-07-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pair', models.CharField(max_length=250)),
                ('time_open', models.CharField(max_length=250)),
                ('time_close', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=250)),
                ('session', models.CharField(max_length=250)),
                ('longorshort', models.CharField(max_length=250)),
                ('entry', models.CharField(max_length=250)),
                ('stop_loss', models.IntegerField()),
                ('outcome', models.CharField(max_length=250)),
                ('rr', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=500)),
            ],
        ),
    ]
