# Generated by Django 5.0.6 on 2024-07-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_note_journal_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='longorshort',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
