# Generated by Django 5.0.6 on 2024-07-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
