# Generated by Django 5.0.6 on 2024-07-11 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_note_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='journal.journal'),
            preserve_default=False,
        ),
    ]
