# Generated by Django 5.0.6 on 2024-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journal_entry_alter_journal_outcome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='longorshort',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='outcome',
            field=models.BooleanField(default=True),
        ),
    ]
