# Generated by Django 5.0.6 on 2024-07-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_alter_journal_longorshort_alter_journal_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='longorshort',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='outcome',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
